#服务启动端口号。钉钉云ECS目前只开放80和22端口
server:
  port: 8011

spring:
  
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html

  http:
    encoding:
      force: true
      charset: UTF-8
        
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
          
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://120.79.241.115:3306/csrxrs?useSSL=false&useUnicode=true
#      username: csrxrs
#      password: 123456
      url: jdbc:mysql://120.79.172.69:3306/assets?useSSL=false&useUnicode=true
      username: assets
      password: tfassets
      initial-size: 1                     #连接池初始大小
      max-active: 10                      #连接池中最大的活跃连接数
      min-idle: 1                         #连接池中最小的活跃连接数
      max-wait: 10000                     #配置获取连接等待超时的时间
      pool-prepared-statements: true    #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false             #是否在获得连接后检测其可用性
      test-on-return: false             #是否在连接放回连接池后检测其可用性
      test-while-idle: true             #是否在连接空闲一段时间后检测其可用性
    
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用